# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  感谢您在这里提出您的第一个问题！我们将会很快与您联系。

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  感谢您提出此拉取请求！我们将会很快与您联系。

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  祝贺您的第一个拉取请求通过了！我们为您感到骄傲！ 

# It is recommend to include as many gifs and emojis as possible

# Configuration for sentiment-bot - https://github.com/behaviorbot/sentiment-bot

# *Required* toxicity threshold between 0 and .99 with the higher numbers being the most toxic
# Anything higher than this threshold will be marked as toxic and commented on
sentimentBotToxicityThreshold: .10

# *Required* Comment to reply with
sentimentBotReplyComment: >
  请务必遵守行为准则，并尊重其他用户！

# Configuration for update-docs - https://github.com/behaviorbot/update-docs

# Comment to be posted to on PRs that don't update documentation
updateDocsComment: >
  感谢您提出此拉取请求！如果您能根据您的更改更新我们的一些文档，我们将不胜感激。
updateDocsWhiteList:
  - 漏洞

updateDocsTargetFiles:
  - README
  - docs/