# These are supported funding model platforms

gitHub: [NewbieXvwu]
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
custom: ['https://space.bilibili.com/505201154','https://gitee.com/NewbieXvwu/MinecraftSkinDownloader']
