name: Python Pull Request Workflow
on:
  push:
    branches:    
      - main
jobs:
 
  qa:
    name: pyinstaller
    runs-on: ubuntu-latest
    steps:
    - name: PyInstaller Build
      # You may pin to the exact commit or the version.
      # uses: eric2788/pyinstaller-build@38c902414aa367793063cc366a58f8f00733177c
      uses: eric2788/pyinstaller-build@0.1.2
      with: 
        # the main python file (without .py)
        main: MinecraftSkinDownloader
        # the dist path
        dist: ./
        # the version of python
        python_version: 3.10.1
        # the version of pyinstaller
        pyinstaller_version: 4.7
        # the output exe name
        artifact: MinecraftSkinDownloader
        # whether to install requirements.txt before build
        use-dependencies: true
        # whether to disppear console terminal
        no-console: false
      
          
