name: Build

on:
  push:
    branches: [ main ]

jobs:
  Build_Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Build Python Exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: MinecraftSkinDownloader
        artifact: MinecraftSkinDownloader
        use-dependencies: false
        python_version: 3.10.1
        
  Build_Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Build Python Exe
        uses: eric2788/pyinstaller-build@master
        with:
          main: MinecraftSkinDownloader
          artifact: MinecraftSkinDownloader
          use-dependencies: false
          python_version: 3.10.1
  Mirror_To_Gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitee.com:NewbieXvwu/MinecraftSkinDownloader
          ssh_private_key:
            ${{ secrets.GITEE_KEY }}
