name: Build

on:
  push:
    branches: [ main ]

jobs:
  Build_Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pip install packages
      run: |
        sudo pip install requests
        sudo pip install ttkthemes
    - name: Test Build Python Exe
      uses: eric2788/pyinstaller-build@patch/icon
      with:
        main: MinecraftSkinDownloader
        artifact: MinecraftSkinDownloader
        use-dependencies: false
        python_version: 3.10.1
        no-console: true
        icon: logo.ico
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build_Result
        path: dist
  Build_Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: pip install packages
        run: |
          sudo pip install requests
          sudo pip install ttkthemes
      - name: Test Build Python Exe
        uses: eric2788/pyinstaller-build@patch/icon
        with:
          main: MinecraftSkinDownloader
          artifact: MinecraftSkinDownloader
          use-dependencies: false
          python_version: 3.10.1
          no-console: true
          icon: logo.ico
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build_Result
          path: dist
  Mirror-To-Gitee:
    runs-on: ubuntu-latest
    name: Sync-GitHub-to-Gitee
    steps:
      - name: Mirror the Github repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/NewbieXvwu
          dst: gitee/NewbieXvwu
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true
