name: Build

on:
  push:
    branches: [ main ]

jobs:
  Build_Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Build Python Exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: MinecraftSkinDownloader
        artifact: MinecraftSkinDownloader
        use-dependencies: false
        python_version: 3.10.1
        
  Build_Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Build Python Exe
        uses: eric2788/pyinstaller-build@master
        with:
          main: MinecraftSkinDownloader
          artifact: MinecraftSkinDownloader
          use-dependencies: false
          python_version: 3.10.1
  Mirror-To-Gitee:
    runs-on: ubuntu-latest
    name: Sync-GitHub-to-Gitee
    steps:
      - name: Mirror the Github repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/NewbieXvwu
          dst: gitee/NewbieXvwu
          dst_key: ${{ secrets.GITEE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "main"
          force_update: true
