name: Build

on:
  push:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Build Python Exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: MinecraftSkinDownloader
        artifact: MinecraftSkinDownloader
        use-dependencies: false
        python_version: 3.10.1
        
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Build Python Exe
        uses: eric2788/pyinstaller-build@master
        with:
          main: MinecraftSkinDownloader
          artifact: MinecraftSkinDownloader
          use-dependencies: false
          python_version: 3.10.1
