name: Python Pull Request Workflow
on:
  push:
    branches:    
      - master
jobs:
 
 
  qa:
    name: pyinstaller
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        with:
          python-version: 3.10
      - name: Run unit tests
        run: |
          pip install pyinstaller
          pyinstaller -F -w -i logo.ico MinecraftSkinDownloader.pyw
          del /F /S /Q __pycache__
          del /F /S /Q build
          del /F /S MinecraftSkinDownloader.spec
          rd __pycache__
          rd build\MinecraftSkinDownloader
          rd build
          move /Y dist\MinecraftSkinDownloader.exe .\MinecraftSkinDownloader.exe
          rd dist
      - name: Wemake Python Stylguide
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
